
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 02 15:44:37 EEST 2012
//----------------------------------------------------

package es.davidfm.compiler.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int NUM_FLOAT = 23;
  public static final int PLUS = 2;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int SEMI = 16;
  public static final int STRG = 26;
  public static final int PRINTLINE = 21;
  public static final int LPAREN = 6;
  public static final int LBRACKET = 10;
  public static final int LBRACE = 8;
  public static final int ID = 25;
  public static final int RBRACKET = 11;
  public static final int BOOLEAN = 14;
  public static final int STRING = 15;
  public static final int COMMA = 17;
  public static final int FLOAT = 13;
  public static final int EOF = 0;
  public static final int MAIN = 19;
  public static final int DIV = 5;
  public static final int MINUS = 3;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int BOOL = 24;
  public static final int INTEGER = 12;
  public static final int NUM_INTEGER = 22;
}

